### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Kadiya99** [junedkh/jmdkh-mltb#13]
After update the bot files. It's not working

2022-11-02 06:38:31,074 - root - INFO - Ready to Start!
2022-11-02 06:38:35,519 - root - INFO - Creating client from BOT_TOKEN
2022-11-02 06:38:35,520 - root - WARNING - MEGA API KEY not provided!
2022-11-02 06:38:35,520 - root - WARNING - MEGA Credentials not provided!
2022-11-02 06:38:35,521 - root - WARNING - BASE_URL not provided!
2022-11-02 06:38:36,132 - root - INFO - Initializing Aria2c
2022-11-02 06:38:42,243 - bot - INFO - Users data has been imported from Database
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 18, in <module>
    from bot.modules import authorize, drive_list, cancel_mirror, mirror_status, mirror_leech, clone, users_settings, ytdlp, \
  File "bot/modules/drive_list.py", line 7, in init bot.modules.drive_list
  File "bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 22, in init bot.helper.mirror_utils.upload_utils.gdriveTools
  File "bot/helper/ext_utils/jmdkh_utils.py", line 262, in init bot.helper.ext_utils.jmdkh_utils
  File "bot/helper/ext_utils/jmdkh_utils.py", line 32, in bot.helper.ext_utils.jmdkh_utils.initiate_sharer_drive
KeyError: 'SHARER_DRIVE_SITE'

**Comment by junedkh** [comment]
Have you Clear your database?

**Comment by Kadiya99** [comment]
Thank You.

I cleared my database and now It's working.

Unfortunately I need to Authorize every group and every users.

Thank You
