### ISSUE TITLE
FSUB_IDS import failed ps: did i do smth wrong ?

### ISSUE THREAD

**Issue by steve472-art** [junedkh/jmdkh-mltb#22]
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 15, in <module>
    from .helper.telegram_helper.message_utils import sendMessage, sendMarkup, editMessage, sendLogFile
  File "bot/helper/telegram_helper/message_utils.py", line 8, in init bot.helper.telegram_helper.message_utils
    from bot.helper.ext_utils.bot_utils import get_readable_message, setInterval
ImportError: cannot import name FSUB_IDS

**Comment by junedkh** [comment]
Do fresh clone

**Comment by steve472-art** [comment]
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 85, in add_download
    media = _dmsg.document or _dmsg.video or _dmsg.audio or None
AttributeError: 'NoneType' object has no attribute 'document'

got a diff one now lmao

**Comment by steve472-art** [comment]
jmdkh-mltb | Exception in thread Thread-4:
jmdkh-mltb | Traceback (most recent call last):
jmdkh-mltb |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
jmdkh-mltb |     self.run()
jmdkh-mltb |   File "/usr/lib/python3.8/threading.py", line 870, in run
jmdkh-mltb |     self._target(*self._args, **self._kwargs)
jmdkh-mltb |   File "bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 88, in bot.helper.mirror_utils.download_utils.telegram_downloader.TelegramDownloadHelper.add_download
jmdkh-mltb | AttributeError: 'NoneType' object has no attribute 'document' 


yea this is the new one ooooooof idk wth causing this 

i used docker and also the docker compose

used value -mltb for build and run

**Comment by steve472-art** [comment]
fixed ehmm im an idiot ...
