### ISSUE TITLE
when using rclone it stuck at 100% 

### ISSUE THREAD

**Issue by mr-m85** [junedkh/jmdkh-mltb#63]
![Screenshot 2023-05-17 031520](https://github.com/junedkh/jmdkh-mltb/assets/106661735/896e474a-fe40-4b3b-a6a4-5bc7d31dd757)

[log (19).txt](https://github.com/junedkh/jmdkh-mltb/files/11493170/log.19.txt)

same problem with onedrive in rclone.conf only

can help me fix this problem

2023-05-17 00:10:39,933 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2023-05-17 00:10:51,976 - root INFO : Creating client from USER_SESSION_STRING [__init__:172]
2023-05-17 00:11:00,132 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:00,292 - pyrogram.connection.connection INFO : Connected! Production DC4 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:00,293 - pyrogram.session.session INFO : NetworkTask started [session:271]
2023-05-17 00:11:00,452 - pyrogram.session.internals.msg_id INFO : Time synced: 2023-05-17 00:11:00.373064 UTC [msg_id:45]
2023-05-17 00:11:01,006 - pyrogram.session.session INFO : Session initialized: Layer 146 [session:131]
2023-05-17 00:11:01,006 - pyrogram.session.session INFO : Device: CPython 3.10.6 - Pyrogram 2.0.59 [session:132]
2023-05-17 00:11:01,006 - pyrogram.session.session INFO : System: Linux 5.15.0-1035-aws (EN) [session:133]
2023-05-17 00:11:01,006 - pyrogram.session.session INFO : Session started [session:148]
2023-05-17 00:11:01,643 - pyrogram.session.session INFO : PingTask started [session:249]
2023-05-17 00:11:01,991 - root WARNING : MEGA Credentials not provided! [__init__:187]
2023-05-17 00:11:08,524 - root INFO : Initializing Aria2c [__init__:550]
2023-05-17 00:11:10,529 - root INFO : Creating client from BOT_TOKEN [__init__:593]
2023-05-17 00:11:20,723 - pyrogram.session.auth INFO : Start creating a new auth key on DC2 [auth:82]
2023-05-17 00:11:20,723 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:20,727 - pyrogram.session.session INFO : NetworkTask stopped [session:287]
2023-05-17 00:11:20,822 - pyrogram.session.session INFO : PingTask stopped [session:268]
2023-05-17 00:11:20,822 - pyrogram.connection.connection INFO : Disconnected [connection:77]
2023-05-17 00:11:20,823 - pyrogram.session.session INFO : Session stopped [session:174]
2023-05-17 00:11:20,823 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:20,884 - pyrogram.connection.connection INFO : Connected! Production DC2 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:20,985 - pyrogram.connection.connection INFO : Connected! Production DC4 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:21,022 - pyrogram.session.session INFO : NetworkTask started [session:271]
2023-05-17 00:11:22,626 - pyrogram.connection.connection INFO : Disconnected [connection:77]
2023-05-17 00:11:22,633 - pyrogram.session.session INFO : NetworkTask stopped [session:287]
2023-05-17 00:11:22,723 - pyrogram.session.session INFO : Session stopped [session:174]
2023-05-17 00:11:22,724 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:22,922 - pyrogram.connection.connection INFO : Connected! Production DC4 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:22,931 - pyrogram.session.session INFO : NetworkTask started [session:271]
2023-05-17 00:11:24,695 - pyrogram.session.session INFO : Session initialized: Layer 146 [session:131]
2023-05-17 00:11:24,696 - pyrogram.session.session INFO : Device: CPython 3.10.6 - Pyrogram 2.0.59 [session:132]
2023-05-17 00:11:24,696 - pyrogram.session.session INFO : System: Linux 5.15.0-1035-aws (EN) [session:133]
2023-05-17 00:11:24,696 - pyrogram.session.session INFO : Session started [session:148]
2023-05-17 00:11:24,696 - pyrogram.session.session INFO : PingTask started [session:249]
2023-05-17 00:11:25,533 - pyrogram.session.auth INFO : Done auth key exchange: DhGenOk [auth:249]
2023-05-17 00:11:25,533 - pyrogram.connection.connection INFO : Disconnected [connection:77]
2023-05-17 00:11:31,732 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:31,929 - pyrogram.connection.connection INFO : Connected! Production DC2 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:31,929 - pyrogram.session.session INFO : NetworkTask started [session:271]
2023-05-17 00:11:33,727 - pyrogram.session.session INFO : Session initialized: Layer 146 [session:131]
2023-05-17 00:11:33,747 - pyrogram.session.session INFO : Device: CPython 3.10.6 - Pyrogram 2.0.59 [session:132]
2023-05-17 00:11:33,748 - pyrogram.session.session INFO : System: Linux 5.15.0-1035-aws (EN) [session:133]
2023-05-17 00:11:33,748 - pyrogram.session.session INFO : Session started [session:148]
2023-05-17 00:11:34,825 - pyrogram.session.session INFO : PingTask started [session:249]
2023-05-17 00:11:35,127 - pyrogram.session.session INFO : PingTask stopped [session:268]
2023-05-17 00:11:35,127 - pyrogram.connection.connection INFO : Disconnected [connection:77]
2023-05-17 00:11:35,130 - pyrogram.session.session INFO : NetworkTask stopped [session:287]
2023-05-17 00:11:35,131 - pyrogram.session.session INFO : Session stopped [session:174]
2023-05-17 00:11:37,724 - pyrogram.session.auth INFO : Start creating a new auth key on DC4 [auth:82]
2023-05-17 00:11:37,724 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:37,888 - pyrogram.connection.connection INFO : Connected! Production DC4 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:43,128 - pyrogram.session.auth INFO : Done auth key exchange: DhGenOk [auth:249]
2023-05-17 00:11:43,128 - pyrogram.connection.connection INFO : Disconnected [connection:77]
2023-05-17 00:11:47,026 - pyrogram.connection.connection INFO : Connecting... [connection:56]
2023-05-17 00:11:47,187 - pyrogram.connection.connection INFO : Connected! Production DC4 - IPv4 - TCPAbridgedO [connection:63]
2023-05-17 00:11:47,188 - pyrogram.session.session INFO : NetworkTask started [session:271]
2023-05-17 00:11:48,595 - pyrogram.session.session INFO : Session initialized: Layer 146 [session:131]
2023-05-17 00:11:48,596 - pyrogram.session.session INFO : Device: CPython 3.10.6 - Pyrogram 2.0.59 [session:132]
2023-05-17 00:11:48,596 - pyrogram.session.session INFO : System: Linux 5.15.0-1035-aws (EN) [session:133]
2023-05-17 00:11:48,596 - pyrogram.session.session INFO : Session started [session:148]
2023-05-17 00:11:48,596 - pyrogram.session.session INFO : PingTask started [session:249]
2023-05-17 00:11:52,729 - pyrogram.dispatcher INFO : Started 1000 HandlerTasks [dispatcher:154]
2023-05-17 00:11:57,329 - bot INFO : Creating Telegraph Account [telegraph_helper:26]
2023-05-17 00:12:09,526 - apscheduler.scheduler INFO : Adding job tentatively -- it will be properly scheduled when the scheduler starts [base:444]
2023-05-17 00:12:09,549 - apscheduler.scheduler INFO : Added job "RSS" to job store "default" [base:885]
2023-05-17 00:12:09,549 - apscheduler.scheduler INFO : Scheduler started [base:171]
2023-05-17 00:12:27,126 - root INFO : Aria2c initializing finished [__init__:560]
2023-05-17 00:12:28,929 - bot INFO : Bot Started! [__main__:220]
2023-05-17 00:12:29,531 - apscheduler.executors.default INFO : Running job "RSS (trigger: interval[0:15:00], next run at: 2023-05-17 00:27:29 UTC)" (scheduled at 2023-05-17 00:12:29.525251+00:00) [base_py3:28]
2023-05-17 00:12:29,550 - apscheduler.scheduler INFO : Paused scheduler job processing [base:217]
2023-05-17 00:12:29,550 - apscheduler.executors.default INFO : Job "RSS (trigger: interval[0:15:00], next run at: 2023-05-17 00:27:29 UTC)" executed successfully [base_py3:41]
2023-05-17 00:13:24,748 - bot INFO : magnet:?xt=urn:btih:C1F5DF015064A6B8970B1023DD30E3C81B66D216&dn=Ravenlok+%28Build+0.88.08+%2B+2+DLCs%2C+MULTi7%29+%5BFitGirl+Repack%5D&tr=udp%3A%2F%2Fopentor.net%3A6969&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=https%3A%2F%2Ftracker.tamersunion.org%3A443%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=http%3A%2F%2Ftracker.gbitt.info%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.ccp.ovh%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce [mirror_leech:236]
2023-05-17 00:13:36,724 - bot INFO : QbitDownload started: Ravenlok (Build 0.88.08 + 2 DLCs, MULTi7) [FitGirl Repack] - Hash: c1f5df015064a6b8970b1023dd30e3c81b66d216 [qbit_download:80]
2023-05-17 00:13:54,742 - web.wserver - INFO - Verified! Hash: c1f5df015064a6b8970b1023dd30e3c81b66d216
2023-05-17 00:14:27,368 - bot INFO : Cleaning unwanted files/folders: /usr/src/app/downloads/334 [fs_utils:99]
2023-05-17 00:14:27,433 - bot INFO : Download completed: Ravenlok (Build 0.88.08 + 2 DLCs, MULTi7) [FitGirl Repack] [tasks_listener:153]
2023-05-17 00:14:27,436 - bot INFO : Upload Name: Ravenlok [FitGirl Repack] [tasks_listener:356]
2023-05-17 00:14:47,879 - bot.helper.mirror_utils.rclone_utils.transfer INFO : Upload Done. Path: OneDrive:Games/Ravenlok [FitGirl Repack] [transfer:274]
2023-05-17 00:14:47,879 - bot INFO : Task Done: Ravenlok [FitGirl Repack] [tasks_listener:371]
2023-05-17 00:14:47,880 - asyncio ERROR : Task exception was never retrieved
future: <Task finished name='Task-1606' coro=<__onDownloadComplete() done, defined at /usr/src/app/bot/helper/listeners/qbit_listener.py:72> exception=KeyError('id')> [__main__:224]
Traceback (most recent call last):
  File "/usr/src/app/bot/helper/listeners/qbit_listener.py", line 86, in __onDownloadComplete
    await listener.onDownloadComplete()
  File "/usr/src/app/bot/helper/listeners/tasks_listener.py", line 362, in onDownloadComplete
    await RCTransfer.upload(path, size)
  File "/usr/src/app/bot/helper/mirror_utils/rclone_utils/transfer.py", line 275, in upload
    await self.__listener.onUploadComplete(link, size, files, folders, mime_type, self.name, destination)
  File "/usr/src/app/bot/helper/listeners/tasks_listener.py", line 419, in onUploadComplete
    drive_id = GoogleDriveHelper.getIdFromUrl(link)
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 122, in getIdFromUrl
    return parse_qs(parsed.query)['id'][0]
KeyError: 'id'
2023-05-17 00:24:51,131 - bot.helper.mirror_utils.rclone_utils.transfer INFO : Cancelling Upload: Ravenlok [FitGirl Repack] [transfer:366]
2023-05-17 00:24:54,530 - bot INFO : Cleaning Download: /usr/src/app/downloads/334 [fs_utils:56]
2023-05-17 00:42:02,370 - bot INFO : magnet:?xt=urn:btih:C1F5DF015064A6B8970B1023DD30E3C81B66D216&dn=Ravenlok+%28Build+0.88.08+%2B+2+DLCs%2C+MULTi7%29+%5BFitGirl+Repack%5D&tr=udp%3A%2F%2Fopentor.net%3A6969&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=https%3A%2F%2Ftracker.tamersunion.org%3A443%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=http%3A%2F%2Ftracker.gbitt.info%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.ccp.ovh%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce [mirror_leech:236]
2023-05-17 00:43:04,474 - bot INFO : magnet:?xt=urn:btih:C1F5DF015064A6B8970B1023DD30E3C81B66D216&dn=Ravenlok+%28Build+0.88.08+%2B+2+DLCs%2C+MULTi7%29+%5BFitGirl+Repack%5D&tr=udp%3A%2F%2Fopentor.net%3A6969&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=https%3A%2F%2Ftracker.tamersunion.org%3A443%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=http%3A%2F%2Ftracker.gbitt.info%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.ccp.ovh%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce [mirror_leech:236]
2023-05-17 00:44:06,499 - bot INFO : magnet:?xt=urn:btih:EEBEB5FB1667557D02508538BFB1E8FF783CD64D&dn=Death+or+Threat+%28v1.0.4%2C+MULTi11%29+%5BFitGirl+Repack%5D&tr=udp%3A%2F%2Fopentor.net%3A6969&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=https%3A%2F%2Ftracker.tamersunion.org%3A443%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=http%3A%2F%2Ftracker.gbitt.info%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.ccp.ovh%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce [mirror_leech:236]
2023-05-17 00:44:14,529 - bot INFO : QbitDownload started: Death or Threat (v1.0.4, MULTi11) [FitGirl Repack] - Hash: eebeb5fb1667557d02508538bfb1e8ff783cd64d [qbit_download:80]
2023-05-17 00:44:37,589 - web.wserver - INFO - Verified! Hash: eebeb5fb1667557d02508538bfb1e8ff783cd64d
2023-05-17 00:45:44,814 - bot INFO : Cleaning unwanted files/folders: /usr/src/app/downloads/355 [fs_utils:99]
2023-05-17 00:45:44,826 - bot INFO : Download completed: Death or Threat (v1.0.4, MULTi11) [FitGirl Repack] [tasks_listener:153]
2023-05-17 00:45:44,829 - bot INFO : Upload Name: Death or Treat [FitGirl Repack] [tasks_listener:356]
2023-05-17 00:45:56,613 - bot.helper.mirror_utils.rclone_utils.transfer INFO : Upload Done. Path: OneDrive:Games/Death or Treat [FitGirl Repack] [transfer:274]
2023-05-17 00:45:56,613 - bot INFO : Task Done: Death or Treat [FitGirl Repack] [tasks_listener:371]
2023-05-17 00:45:56,614 - asyncio ERROR : Task exception was never retrieved
future: <Task finished name='Task-5589' coro=<__onDownloadComplete() done, defined at /usr/src/app/bot/helper/listeners/qbit_listener.py:72> exception=KeyError('id')> [__main__:224]
Traceback (most recent call last):
  File "/usr/src/app/bot/helper/listeners/qbit_listener.py", line 86, in __onDownloadComplete
    await listener.onDownloadComplete()
  File "/usr/src/app/bot/helper/listeners/tasks_listener.py", line 362, in onDownloadComplete
    await RCTransfer.upload(path, size)
  File "/usr/src/app/bot/helper/mirror_utils/rclone_utils/transfer.py", line 275, in upload
    await self.__listener.onUploadComplete(link, size, files, folders, mime_type, self.name, destination)
  File "/usr/src/app/bot/helper/listeners/tasks_listener.py", line 419, in onUploadComplete
    drive_id = GoogleDriveHelper.getIdFromUrl(link)
  File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 122, in getIdFromUrl
    return parse_qs(parsed.query)['id'][0]
KeyError: 'id'

**Comment by junedkh** [comment]
Fixed
